### GET request to example server
### Create a User
### POST request to create multiple Users
POST http://localhost:8080/users/add
Content-Type: application/json



{"name": "KK",
  "email": "alinaaa.dimova@student.kdg.com",
  "password": "1111111a", "pet":{"id": 1}}




