### GET request to example server
### Create a Schedule
### POST request to create multiple Schedules
POST http://localhost:8080/schedules/add
Content-Type: application/json

[
{
  "frequency": "DAILY",
  "timeToFeed": "12:30",
  "feeder": {"id": 1}

}
]