### GET request to example server
### Create a Feeder
### POST request to create multiple Schedules
POST http://localhost:8080/feeders/add
Content-Type: application/json

[
{
"bowlWeight": 150,
  "reservoirLevel": 80.0, "portion": 5.0, "schedule": 1}
  ]


