### GET request to example server
### Create a User
### POST request to create multiple Users
POST http://localhost:8080/users/add
Content-Type: application/json



  {"name": "Alina d",
    "email": "alice.jddd@kdg.com",
    "password": "n4545453"}




