### GET request to example server
### Create a Feeder
### POST request to create multiple Schedules
POST http://localhost:80/feeders/add
Content-Type: application/json

{

  "bowlWeight": 12.3,
  "petWeight": 60.1,
  "reservoirLevel": 80.5
}

