### GET request to example server
### Create a Feeder
### POST request to create multiple Schedules
POST http://localhost:8080/feeders/add
Content-Type: application/json

{
  "reservoirLevel": 80.5,
  "bowlWeight": 12.3
}

