### GET request to example server
### Create a PetDataLog
### POST request to create multiple PetDataLogs
POST http://localhost:8080/data-logs/add
Content-Type: application/json

{
  "petWeight": 15.0,
  "animalType": "HAMSTER",
  "pet": {
    "id": 1
  },
  "feeder": {
    "portion": 15,
    "id": 1
  }
}