### GET request to example server
### Create a Pet
### POST request to create multiple Pets
POST http://localhost:80/pets/add
Content-Type: application/json


{
  "age": 1,
  "animalType": "SIBERIAN",
  "name": "Hammy",
  "petWeight": 0.45,
  "user" : {"id": 1}

}


