### GET request to example server
### Create a Pet
### POST request to create multiple Pets
POST http://localhost:8080/pets/add
Content-Type: application/json


{
  "name": "Hammy",
  "age": 2,
  "animalType": "HAMSTER",
  "petWeight": 0.45,
  "user" : {"id": 2}

}


