### GET request to example server
### Create a PetDataLog
### POST request to create multiple Schedules
POST http://localhost:8080/data-logs/add
Content-Type: application/json

{
  "pet": {
    "id": 1
  },
  "petWeight": 350,
  "foodAte": 15,
  "animalType": "HAMSTER"
}