### GET request to example server
POST http://localhost:80/api/descriptive
Content-Type: application/json

{
  "pet_data_log_descriptive": [
    {
      "age_weeks": 4,
      "bowl_weight": 1.8,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 18.51,
      "reservoir_height": 30,
      "sex": "Male",
      "timestamp": "2024-09-29 16:46:17",
      "feeder_id": 1
    },
    {
      "age_weeks": 5,
      "bowl_weight": 2.1,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 19.8,
      "reservoir_height": 29.7,
      "sex": "Male",
      "timestamp": "2024-10-05 10:32:04",
      "feeder_id": 1
    },
    {
      "age_weeks": 6,
      "bowl_weight": 2.23,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 21.1,
      "reservoir_height": 29.4,
      "sex": "Male",
      "timestamp": "2024-10-12 16:50:06",
      "feeder_id": 1
    },
    {
      "age_weeks": 7,
      "bowl_weight": 2.1,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 20.6,
      "reservoir_height": 28.9,
      "sex": "Male",
      "timestamp": "2024-10-19 20:50:14",
      "feeder_id": 1
    },
    {
      "age_weeks": 8,
      "bowl_weight": 2.4,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 21.8,
      "reservoir_height": 28.6,
      "sex": "Male",
      "timestamp": "2024-10-26 10:39:21",
      "feeder_id": 1
    },
    {
      "age_weeks": 9,
      "bowl_weight": 2.7,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 23.5,
      "reservoir_height": 28.4,
      "sex": "Male",
      "timestamp": "2024-11-03 19:43:26",
      "feeder_id": 1
    },
    {
      "age_weeks": 10,
      "bowl_weight": 2.84,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 22.9,
      "reservoir_height": 28.8,
      "sex": "Male",
      "timestamp": "2024-11-10 09:09:17",
      "feeder_id": 1
    },
    {
      "age_weeks": 11,
      "bowl_weight": 2.67,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 24.34,
      "reservoir_height": 28.5,
      "sex": "Male",
      "timestamp": "2024-11-17 09:14:07",
      "feeder_id": 1
    },
    {
      "age_weeks": 12,
      "bowl_weight": 2.91,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 25.1,
      "reservoir_height": 28.8,
      "sex": "Male",
      "timestamp": "2024-11-24 10:23:07",
      "feeder_id": 1
    },
    {
      "age_weeks": 13,
      "bowl_weight": 2.6,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 24.9,
      "reservoir_height": 28.3,
      "sex": "Male",
      "timestamp": "2024-12-01 09:14:30",
      "feeder_id": 1
    },
    {
      "age_weeks": 14,
      "bowl_weight": 3.12,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 25.5,
      "reservoir_height": 28,
      "sex": "Male",
      "timestamp": "2024-12-08 09:14:07",
      "feeder_id": 1
    },
    {
      "age_weeks": 15,
      "bowl_weight": 3.5,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 26.6,
      "reservoir_height": 27.2,
      "sex": "Male",
      "timestamp": "2024-12-15 09:12:05",
      "feeder_id": 1
    },
    {
      "age_weeks": 16,
      "bowl_weight": 3.67,
      "breed": "DWARF_CAMPBELL_RUSSIAN",
      "pet_weight": 27,
      "reservoir_height": 26.8,
      "sex": "Male",
      "timestamp": "2024-12-22 10:45:05",
      "feeder_id": 1
    }
  ]
}