### GET request to example server
POST http://localhost:80/api/sendData
Content-Type: application/json

{
  "id": 1,
  "age_weeks": 8,
  "weight_grams": 148.29,
  "breed": "Syrian",
  "food_intake": 10.33,
  "reservoir_height": 0.3,
  "sex": "Female"
}