### GET request to example server
POST http://localhost:80/api/sendData
Content-Type: application/json

{
  "id": 1,
  "age_weeks": 40,
  "weight_grams": 57,
  "breed": "Syrian",
  "food_intake": 17,
  "sex": "Female"
}

